app:
  name: MetaCMSWorkerGit
  port: 3001

logger:
  prettyPrint:
    colorize: true
    levelFirst: true
    translateTime: mm/dd/yy hh:mm:ss TT

git:
  baseDirName: worker-git-data

sevenZip:
  binName: 7zz

backend:
  host:
  port:
